import { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Trelo 2.0 Clone",
  description: "Generated by devLeopar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}
